apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wanhfp0zk-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe-java-quarkus:0cc3b3ec40241a5bd806deebd8e6583c399d9996@sha256:71eb51f307ba941247e9b8cad4e2279371533fc513f0e44d554579e9a27369cc
          name: container-image
